import { useState } from 'react'
import { trustPageById, type TrustPageId } from '../data/trustPages'
import { EMBERVILLE_SOURCES, type EmbervillePageId } from '../data/emberville'
import { experienceEnabled } from './rollout'

const directions = ['Melee', 'Magic', 'Ranged', 'Hybrid']
const directionNotes = ['Positioning, timing, and close-range weapon interactions.', 'Keep spell-focused plans separate until exact class and skill records are verified.', 'Plan around distance while weapon and class records remain in review.', 'Depends on confirmed inheritance compatibility; no combination is validated yet.']
function EmberTask({ pageId }: { pageId: EmbervillePageId }) {
  const [direction, setDirection] = useState('Melee')
  const [comparison, setComparison] = useState('Magic')
  const [stage, setStage] = useState(0)
  const stages = pageId === 'inheritance' ? ['Learn a class', 'Review active or passive skill', 'Check destination compatibility'] : ['Combat class system', 'Weapons and combos', 'Progression and inheritance']
  return <>{pageId === 'builds' ? <><h2>Compare planning directions</h2><div className="legacy-task-grid"><label>First direction<select value={direction} onChange={(event) => setDirection(event.target.value)}>{directions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Second direction<select value={comparison} onChange={(event) => setComparison(event.target.value)}>{directions.map((item) => <option key={item}>{item}</option>)}</select></label></div><p role="status">{direction === comparison ? 'Same direction selected; there is no difference to compare.' : `${direction}: ${directionNotes[directions.indexOf(direction)]} ${comparison}: ${directionNotes[directions.indexOf(comparison)]}`}</p><p>These are planning lenses, not tested builds or power rankings. Exact class, weapon and skill combinations remain unknown.</p><a href="/emberville#planner">Record this direction in the planner</a></> : pageId === 'planner' ? <><h2>Set up your planning session</h2><p>Choose the part of your idea to work on. Concrete class, weapon and skill records remain locked pending verification.</p><nav className="legacy-task-route-grid" aria-label="Emberville planning tasks"><a href="#planner">Choose a direction and write local notes</a><a href="/emberville-builds">Compare two combat directions</a><a href="/emberville-classes">Review class-system evidence</a><a href="/emberville-skill-inheritance">Trace the inheritance workflow</a></nav></> : <><h2>{pageId === 'classes' ? 'Inspect the class planning requirements' : 'Trace an inheritance plan'}</h2><div className="legacy-task-actions">{stages.map((item, index) => <button type="button" key={item} aria-pressed={stage === index} onClick={() => setStage(index)}>{index + 1}. {item}</button>)}</div><h3>{stages[stage]}</h3><p role="status">{pageId === 'classes' ? ['Confirmed: a combat class system with classes that can be changed. Exact selectable class names remain in review.', 'Confirmed: equipment and weapon-bound combos are part of combat. Exact weapon records and class relationships remain in review.', 'Confirmed: learned classes can contribute active and passive skills through inheritance. Unlock thresholds and compatibility rules remain in review.'][stage] : ['Start with a learned class. Classes can be changed; the exact unlock requirements are not verified here.', 'Both active and passive skill inheritance are confirmed systems. Individual skill names, ranks and effects are not verified here.', 'A destination needs verified inheritance rules. No source-to-destination combination can be validated with the current records.'][stage]}</p><a href={EMBERVILLE_SOURCES[0].href} target="_blank" rel="noreferrer">Read the official system description</a><a href="/emberville#planner">Keep an unverified idea in local planner notes</a></>}</>
}

function TrustTask({ pageId }: { pageId: TrustPageId }) {
  const page = trustPageById(pageId)
  const [reportType, setReportType] = useState('Game data')
  return <><h2>{pageId === 'about' ? 'Explore the project and its evidence' : pageId === 'privacy' ? 'Find the privacy topic you need' : 'Prepare a useful report'}</h2><nav aria-label={`${page.title} sections`} className="legacy-task-actions">{page.sections.map((section) => <a key={section.heading} href={`#${section.heading.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`}>{section.heading}</a>)}</nav>{pageId === 'contact' && <><label>Report topic<select value={reportType} onChange={(event) => setReportType(event.target.value)}>{['Game data', 'Bug', 'Feature request', 'Other'].map((value) => <option key={value}>{value}</option>)}</select></label><p role="status">{reportType === 'Game data' ? 'Include the game, talent or skill name, client build, exact text and a public source link.' : reportType === 'Bug' ? 'Include the affected page, steps to reproduce, expected result and what happened.' : reportType === 'Feature request' ? 'Describe the task you want to complete and where the current tool gets in the way.' : 'Describe your question with enough non-sensitive context to review it.'}</p><button type="button" onClick={() => document.querySelector<HTMLButtonElement>('.feedback-trigger')?.click()}>Open private feedback form</button></>}{pageId === 'about' && <a href="/wow-forever-paladin-beta-talent-changes">Inspect a reviewed data comparison</a>}{pageId === 'privacy' && <a href="/contact">Ask a privacy question through the feedback form</a>}</>
}

export default function LegacyIntentExperience({ path }: { path: string }) {
  if (!experienceEnabled(path)) return null
  let content
  if (['/about', '/contact', '/privacy'].includes(path)) content = <TrustTask pageId={path.slice(1) as TrustPageId} />
  else if (['/emberville', '/emberville-builds', '/emberville-classes', '/emberville-skill-inheritance'].includes(path)) content = <EmberTask pageId={path === '/emberville' ? 'planner' : path === '/emberville-builds' ? 'builds' : path === '/emberville-classes' ? 'classes' : 'inheritance'} />
  else return null
  return <section className="legacy-intent-task shell" data-intent-experience={path} aria-label="Page planning task">{content}</section>
}
