import LegacyIntentExperience from './experiences/LegacyIntentExperience'
import { experienceEnabled } from './experiences/rollout'
import { ArrowRight, BookOpen, Check, CircleHelp, Flame, Gamepad2, GitBranch, ShieldCheck, Sparkles, Swords } from 'lucide-react'
import EmbervillePlanner from './EmbervillePlanner'
import EmbervilleShell from './EmbervilleShell'
import { EMBERVILLE_EDITORIAL, EMBERVILLE_MECHANICS, EMBERVILLE_PAGES, EMBERVILLE_SOURCES, EMBERVILLE_STATUS, embervillePageById, type EmbervillePageId } from './data/emberville'

const buildDirections = [
  ['Melee builds', 'Positioning and close-range combat.', Swords],
  ['Magic builds', 'Spell-focused build directions.', Sparkles],
  ['Ranged builds', 'Distance and precision.', Gamepad2],
  ['Hybrid builds', 'Mix learned skills through inheritance.', GitBranch],
] as const

function StatusStrip() { return <div className="ember-status"><span><Flame />{EMBERVILLE_STATUS.phase}</span><span><ShieldCheck />Confirmed mechanics</span><span>Updated {EMBERVILLE_STATUS.updated}</span></div> }
function Sources() { return <section className="ember-section source-section"><div><p className="ember-kicker">TRANSPARENT DATA</p><h2>What is officially confirmed</h2><p>We publish confirmed systems and clearly label anything still under review. Specific class, weapon, skill, and balance data will appear only after reliable source verification.</p></div><ul>{EMBERVILLE_SOURCES.map((source) => <li key={source.href}><a href={source.href} rel="noreferrer" target="_blank">{source.label}<ArrowRight size={16} /></a></li>)}</ul></section> }
function Related({ current }: { current: EmbervillePageId }) { return <section className="ember-section"><p className="ember-kicker">EXPLORE EMBERVILLE</p><h2>Related tools and guides</h2><div className="related-grid">{EMBERVILLE_PAGES.filter((page) => page.id !== current).map((page) => <a href={`/${page.slug}`} key={page.id}><strong>{page.title}</strong><span>{page.description}</span><ArrowRight /></a>)}</div></section> }
function Editorial({ pageId }: { pageId: EmbervillePageId }) { return <div className="ember-editorial">{EMBERVILLE_EDITORIAL[pageId].map((section) => <section className="ember-section" key={section.heading}><p className="ember-kicker">{pageId === 'planner' ? 'PLANNER DATA' : pageId === 'builds' ? 'BUILD SYSTEM' : pageId === 'classes' ? 'CLASS DATA' : 'INHERITANCE DATA'}</p><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((item) => <li key={item}><Check /> <span>{item}</span></li>)}</ul>}</section>)}</div> }

export default function EmbervillePage({ pageId }: { pageId: EmbervillePageId }) {
  const page = embervillePageById(pageId)
  return <EmbervilleShell><main className={experienceEnabled(`/${page.slug}`) ? 'legacy-experience-page' : undefined}>
    <section className="ember-hero" style={{ '--ember-hero': `url(${page.heroImage})` } as React.CSSProperties}><div className="hero-copy"><p className="ember-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.description}</p><StatusStrip /><div className="hero-actions"><a className="ember-button" href={pageId === 'planner' ? '#planner' : '/emberville'}>{pageId === 'planner' ? 'Open Planner' : 'Open Build Planner'}<ArrowRight /></a>{pageId !== 'classes' && <a className="ember-button secondary" href="/emberville-classes">View Classes</a>}</div></div></section>
      <LegacyIntentExperience path={`/${page.slug}`} />
    {pageId === 'planner' && <><EmbervillePlanner /><section className="ember-section"><p className="ember-kicker">CONFIRMED TODAY</p><h2>Build around systems we can verify</h2><div className="mechanic-grid">{EMBERVILLE_MECHANICS.map((item) => <div key={item}><Check />{item}</div>)}</div></section></>}
    {pageId === 'builds' && <><section className="ember-section"><p className="ember-kicker">EARLY BUILD DIRECTIONS</p><h2>Explore a playstyle</h2><p>These are planning categories based on the game’s confirmed combat directions. They are not claims about best builds or final balance.</p><div className="direction-grid">{buildDirections.map(([title, body, Icon]) => <article key={title}><Icon /><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="ember-section steps"><h2>Build planning principles</h2><ol><li><strong>Choose a direction</strong><span>Start with the combat style you want to explore.</span></li><li><strong>Match future class data</strong><span>Use verified class information as it becomes available.</span></li><li><strong>Plan inherited skills</strong><span>Consider active and passive skills learned from other classes.</span></li><li><strong>Refine after Early Access</strong><span>Test and iterate when full values are public.</span></li></ol></section></>}
    {pageId === 'classes' && <><section className="ember-section"><p className="ember-kicker">CLASS SYSTEM</p><h2>What we know before Early Access</h2><div className="fact-layout"><div className="mechanic-grid">{EMBERVILLE_MECHANICS.slice(2).map((item) => <div key={item}><Check />{item}</div>)}</div><article className="ember-panel"><CircleHelp /><h3>Names and exact rules are still in review</h3><p>The developer has discussed a planned class and weapon system. We will add individual records only when names, identifiers, and mechanics can be verified consistently.</p></article></div></section><section className="ember-section"><h2>Why classes matter to the planner</h2><div className="direction-grid"><article><Swords /><h3>Starting identity</h3><p>Your current combat class provides the foundation for a build.</p></article><article><BookOpen /><h3>Learned options</h3><p>Changing classes expands the pool of skills available to learn.</p></article><article><GitBranch /><h3>Inheritance</h3><p>Confirmed active and passive inheritance creates room for flexible combinations.</p></article></div></section></>}
    {pageId === 'inheritance' && <><section className="inheritance-flow ember-section" style={{ '--flow-image': 'url(/images/emberville/inheritance-flow.jpg)' } as React.CSSProperties}><p className="ember-kicker">CONFIRMED MECHANIC</p><h2>How skill inheritance shapes a build</h2><div className="flow-row"><article><Swords /><h3>Base class</h3><p>Begin with a combat identity.</p></article><ArrowRight /><article><BookOpen /><h3>Learn another class</h3><p>Expand your available skills.</p></article><ArrowRight /><article><GitBranch /><h3>Inherit skills</h3><p>Use confirmed active and passive inheritance.</p></article><ArrowRight /><article><Sparkles /><h3>Shape a build</h3><p>Create a direction to test when full data arrives.</p></article></div></section><section className="ember-section"><h2>Confirmed boundaries</h2><div className="fact-layout"><div><p>Active and passive skill inheritance is officially described as part of Emberville’s class system. This creates real planning value before exact skills are published.</p><p>Slot limits, costs, thresholds, compatibility rules, and optimal combinations remain unconfirmed here. The planner will not invent them.</p></div><div className="mechanic-grid"><div><Check />Active skill inheritance</div><div><Check />Passive skill inheritance</div><div><Check />Classes can be changed</div><div><CircleHelp />Full data pending</div></div></div></section></>}
    <Editorial pageId={pageId} /><Sources /><Related current={pageId} />
  </main></EmbervilleShell>
}
