import { ArrowDown, ArrowRight, BookOpen, Leaf, Music2, Sprout, Sun } from 'lucide-react'
import GlimmerwickPlanner from './GlimmerwickPlanner'
import { GLIMMERWICK_MECHANICS, GLIMMERWICK_REFERENCE, GLIMMERWICK_SOURCES } from './data/glimmerwick'

export default function GlimmerwickPage() {
  return <div className="glimmerwick-site">
    <header className="gw-header"><a className="gw-brand" href="/">BuildForge<span>Tools</span></a><nav aria-label="Glimmerwick tools"><a href="#garden-planner">Garden planner</a><a href="#gw-reference">Game reference</a><a href="/">All game tools <ArrowRight size={14} /></a></nav></header>
    <main>
      <section className="gw-hero"><div className="gw-hero-copy"><p className="gw-eyebrow"><Music2 size={15} /> A LITTLE PLANNING, A LITTLE MAGIC</p><h1>Songs of Glimmerwick <span>Garden Planner</span></h1><p>Keep your planting notes in one place. Work out when to check the next harvest, then leave room in your day for a song.</p><div className="gw-hero-meta"><span>Demo available</span><span>Release listed: Sep 30, 2026</span></div><a className="gw-button" href="#garden-planner">Plan your garden <ArrowDown size={16} /></a></div><div className="gw-garden-art" aria-hidden="true"><div className="gw-art-heading"><span>THE GARDEN NOTEBOOK</span><Sun size={28} /></div><div className="gw-art-beds">{Array.from({ length: 9 }, (_, index) => <div key={index} className={index % 3 === 0 ? 'gw-art-flower' : ''}><Sprout /></div>)}</div><div className="gw-art-caption"><Music2 size={19} /><span>Plant. Observe. Make a note.</span></div></div></section>
      <GlimmerwickPlanner />
      <section className="gw-guide" aria-labelledby="gw-guide-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">A NOTEBOOK YOU CAN REVISE</p><h2 id="gw-guide-title">From an observation to a plan</h2></div><BookOpen size={25} /></div><div className="gw-guide-grid"><article><span>01</span><h3>Start with what you planted</h3><p>Use the crop name you see in your game. Record the plant count, planting day and a duration you have measured or want to test. Separate plantings can use different timings, even when they share a crop name.</p></article><article><span>02</span><h3>Check your next garden session</h3><p>Update your day counter as you play. The schedule sorts by the estimated ready day and flags rows worth checking. A future planting is a plan you can edit; a ready row is a reminder to inspect the garden.</p></article><article><span>03</span><h3>Keep the lesson, change the estimate</h3><p>When an observation differs, edit the row rather than treating the first number as a rule. Notes can record a song, watering experiment or quest ingredient. Remove harvested rows and export the rest as a spreadsheet.</p></article></div></section>
      <section className="gw-reference" id="gw-reference" aria-labelledby="gw-reference-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">OFFICIAL SYSTEMS, CLEAR LIMITS</p><h2 id="gw-reference-title">What the game confirms</h2></div><span>Sources checked {GLIMMERWICK_REFERENCE.checkedAt}</span></div><div className="gw-reference-grid">{GLIMMERWICK_MECHANICS.map(item => <article key={item.title}><Leaf size={19} /><h3>{item.title}</h3><p>{item.description}</p><a href={item.sourceHref} target="_blank" rel="noreferrer">Official reference <ArrowRight size={14} /></a></article>)}</div><div className="gw-source-box"><div><h3>A planner, not a complete crop database</h3><p>These references confirm the systems. They do not establish every crop’s growth time, yield or spell interaction. This tool uses your own inputs and makes no claim that an estimate is a verified game value.</p><p>Steam currently lists a September 30, 2026 release and a playable Demo. The reference date records when that information was checked; Demo timings may differ from the full game.</p></div><nav aria-label="Official game sources">{GLIMMERWICK_SOURCES.map(source => <a key={source.href} href={source.href} target="_blank" rel="noreferrer">{source.label}<ArrowRight size={15} /></a>)}</nav></div></section>
      <section className="gw-faq" aria-labelledby="gw-faq-title"><p className="gw-eyebrow">BEFORE YOU START</p><h2 id="gw-faq-title">Garden planner questions</h2><details><summary>Does this include confirmed crop times or a skill calculator?</summary><p>No. Enter growth durations you observe yourself. This page does not invent crop data, skill ranks or a best build. The official references above explain why gardening, songs and character progression belong together, while the tool remains a personal planning notebook.</p></details><details><summary>How are harvest days calculated?</summary><p>The estimate adds your observed growth duration to the planting day. A planting on Day 3 with four elapsed growth days is scheduled for Day 7. Use a day count of your own; no month or season length is assumed. Watering and other effects can change the actual result.</p></details><details><summary>Where is my garden plan saved?</summary><p>In this browser’s local storage. It is not uploaded to BuildForgeTools and does not sync across devices. Clearing browser data can erase it. Export CSV for a backup; if local storage is blocked, the tool still works during the session.</p></details></section>
    </main>
    <footer className="gw-footer"><div><a className="gw-brand" href="/">BuildForge<span>Tools</span></a><p>An independent, community-made planning tool. Not affiliated with Eastshade Studios.</p></div><nav aria-label="Site information"><a href="/">Game tools</a><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a></nav></footer>
  </div>
}
