import { ArrowDown, ArrowRight, BookOpen, Leaf, Music2, Sprout, Sun } from 'lucide-react'
import GlimmerwickPlanner from './GlimmerwickPlanner'
import { GLIMMERWICK_GARDEN_RULES, GLIMMERWICK_MECHANICS, GLIMMERWICK_REFERENCE, GLIMMERWICK_REVIEWED_CROPS, GLIMMERWICK_SOURCES } from './data/glimmerwick'

export default function GlimmerwickPage() {
  return <div className="glimmerwick-site">
    <header className="gw-header"><a className="gw-brand" href="/">BuildForge<span>Tools</span></a><nav aria-label="Glimmerwick tools"><a href="#garden-planner">Garden planner</a><a href="#gw-reference">Game reference</a><a href="/">All game tools <ArrowRight size={14} /></a></nav></header>
    <main>
      <section className="gw-hero"><div className="gw-hero-copy"><p className="gw-eyebrow"><Music2 size={15} /> A LITTLE PLANNING, A LITTLE MAGIC</p><h1>Songs of Glimmerwick <span>Garden Planner</span></h1><p>Keep your planting notes in one place. Work out when to check the next harvest, then leave room in your day for a song.</p><div className="gw-hero-meta"><span>Released Sep 30, 2026</span><span>Crop data reviewed Oct 1, 2026</span></div><a className="gw-button" href="#garden-planner">Plan your garden <ArrowDown size={16} /></a></div><div className="gw-garden-art" aria-hidden="true"><div className="gw-art-heading"><span>THE GARDEN NOTEBOOK</span><Sun size={28} /></div><div className="gw-art-beds">{Array.from({ length: 9 }, (_, index) => <div key={index} className={index % 3 === 0 ? 'gw-art-flower' : ''}><Sprout /></div>)}</div><div className="gw-art-caption"><Music2 size={19} /><span>Plant. Observe. Make a note.</span></div></div></section>
      <nav className="gw-practical-links" aria-label="Glimmerwick practical help"><a href="/songs-of-glimmerwick-first-days">Continue your first-days checklist →</a><a href="/songs-of-glimmerwick-spellcasting#spellcasting-help">Find help casting a song →</a><a href="/songs-of-glimmerwick-garden-well#garden-well-help">Missing watering can? · 1.03 help →</a></nav>
      <GlimmerwickPlanner />
      <section className="gw-reference gw-crop-evidence" aria-labelledby="gw-crop-evidence-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">LAUNCH DATA REVIEW</p><h2 id="gw-crop-evidence-title">Crops we can name, values still to verify</h2></div><span>Reviewed {GLIMMERWICK_REFERENCE.checkedAt}</span></div><p className="gw-tool-intro">These crop names appear in Demo footage or a firsthand launch playthrough. Neither source establishes a reliable growth duration, seed price, harvest yield or season for the full release. Select a name above to start a personal planting; add timing only after observing it in your game.</p><div className="gw-table-scroll"><table className="gw-evidence-table" aria-label="Songs of Glimmerwick crop evidence"><thead><tr><th>Crop</th><th>Growth days</th><th>Seed price</th><th>Yield</th><th>Season</th><th>Evidence</th></tr></thead><tbody>{GLIMMERWICK_REVIEWED_CROPS.map(crop => <tr key={crop.id}><th scope="row">{crop.name}</th><td>Not verified</td><td>Not verified</td><td>Not verified</td><td>Not verified</td><td><a href={crop.sources[0].href} target="_blank" rel="noreferrer">{crop.version} ↗</a></td></tr>)}</tbody></table></div></section>
      <section className="gw-reference gw-garden-reference" aria-labelledby="gw-garden-rules-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">DEMO EVIDENCE, BESIDE YOUR PLAN</p><h2 id="gw-garden-rules-title">Garden rules you can check</h2></div><span>Reviewed {GLIMMERWICK_REFERENCE.checkedAt}</span></div><p className="gw-tool-intro">Developer notes and public Demo footage provide the references below. They are separate from the growth times you enter. These Demo rules have not yet been independently reconfirmed in the released game.</p><div className="gw-reference-grid">{GLIMMERWICK_GARDEN_RULES.map(rule => <article key={rule.id}><span className="gw-reference-evidence">{rule.verificationStatus === 'official' ? 'Developer note' : 'Demo footage reviewed'}</span><h3>{rule.title}</h3><p>{rule.description}</p><small>{rule.version}</small><a href={rule.sourceHref} target="_blank" rel="noreferrer">{rule.sourceLabel}<ArrowRight size={14} /></a>{'footageHref' in rule && <a href={rule.footageHref} target="_blank" rel="noreferrer">Tilling tutorial · 47:47<ArrowRight size={14} /></a>}</article>)}</div></section>
      <section className="gw-guide" aria-labelledby="gw-guide-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">A NOTEBOOK YOU CAN REVISE</p><h2 id="gw-guide-title">From an observation to a plan</h2></div><BookOpen size={25} /></div><div className="gw-guide-grid"><article><span>01</span><h3>Start with what you planted</h3><p>Use the crop name you see in your game. Record the plant count, planting day and a duration you have measured or want to test. Separate plantings can use different timings, even when they share a crop name.</p></article><article><span>02</span><h3>Check your next garden session</h3><p>Update your day counter as you play. The schedule sorts by the estimated ready day and flags rows worth checking. A future planting is a plan you can edit; a ready row is a reminder to inspect the garden.</p></article><article><span>03</span><h3>Keep the lesson, change the estimate</h3><p>When an observation differs, edit the row rather than treating the first number as a rule. Notes can record a song, watering experiment or quest ingredient. Record a harvest to keep the elapsed days for that planting. Keep the observation in your notebook, or remove the row and export the rest as a spreadsheet.</p></article></div></section>
      <section className="gw-reference" id="gw-reference" aria-labelledby="gw-reference-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">OFFICIAL SYSTEMS, CLEAR LIMITS</p><h2 id="gw-reference-title">What the game confirms</h2></div><span>Sources checked {GLIMMERWICK_REFERENCE.checkedAt}</span></div><div className="gw-reference-grid">{GLIMMERWICK_MECHANICS.map(item => <article key={item.title}><Leaf size={19} /><h3>{item.title}</h3><p>{item.description}</p><a href={item.sourceHref} target="_blank" rel="noreferrer">Official reference <ArrowRight size={14} /></a></article>)}</div><div className="gw-source-box"><div><h3>A planner, not a complete crop database</h3><p>These references confirm the systems. They do not establish every crop’s growth time, yield or spell interaction. This tool uses your own inputs and makes no claim that an estimate is a verified game value.</p><p>Steam confirms the September 30, 2026 release. The review date records when sources were checked, not a verified game build. Demo observations may differ from the full release.</p></div><nav aria-label="Official game sources">{GLIMMERWICK_SOURCES.map(source => <a key={source.href} href={source.href} target="_blank" rel="noreferrer">{source.label}<ArrowRight size={15} /></a>)}</nav></div></section>
      <section className="gw-reference gw-launch-links" aria-labelledby="gw-launch-links-title"><div className="gw-section-heading"><div><p className="gw-eyebrow">KEEP EXPLORING</p><h2 id="gw-launch-links-title">More Songs of Glimmerwick tools</h2></div></div><nav aria-label="Songs of Glimmerwick tools"><a href="/songs-of-glimmerwick-first-days"><strong>First Days Checklist</strong><span>Track school supplies and early campus steps.</span><ArrowRight size={17} /></a><a href="/songs-of-glimmerwick-spellcasting"><strong>Spellcasting Basics</strong><span>See how Song of Tilling and practice relate to casting.</span><ArrowRight size={17} /></a><a href="/songs-of-glimmerwick-garden-well"><strong>Garden Well Sell Planner</strong><span>Keep what you need and estimate a sale with your own prices.</span><ArrowRight size={17} /></a></nav></section>
      <section className="gw-faq" aria-labelledby="gw-faq-title"><p className="gw-eyebrow">BEFORE YOU START</p><h2 id="gw-faq-title">Garden planner questions</h2><details><summary>Does this include confirmed crop times or a skill calculator?</summary><p>Basil, Marjoram and Cranberries are source-linked crop names. Their growth time, yield, seed price and season are not verified for the launch build. You can save a planting without a duration and record an actual harvest using your current garden day. These remain your observations, not official defaults. The official references above explain why gardening, songs and character progression belong together, while the tool remains a personal planning notebook.</p></details><details><summary>How are harvest days calculated?</summary><p>The estimate adds your observed growth duration to the planting day. A planting on Day 3 with four elapsed growth days is scheduled for Day 7. Use a day count of your own; no month or season length is assumed. Watering and other effects can change the actual result.</p></details><details><summary>Where is my garden plan saved?</summary><p>In this browser’s local storage. It is not uploaded to BuildForgeTools and does not sync across devices. Clearing browser data can erase it. Export CSV for a backup; if local storage is blocked, the tool still works during the session.</p></details></section>
    </main>
    <footer className="gw-footer"><div><a className="gw-brand" href="/">BuildForge<span>Tools</span></a><p>An independent, community-made planning tool. Not affiliated with Eastshade Studios.</p></div><nav aria-label="Site information"><a href="/">Game tools</a><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a></nav></footer>
  </div>
}
