import { useState } from 'react'
import { PALADIN_COMPARISON_ROUTES, snapshotGate } from './data/paladinDecisionTools'
import { talents } from './data/talents'
import { track } from './lib/analytics'
import PaladinRouteTimeline from './PaladinRouteTimeline'
import SiteFooter from './SiteFooter'
import PaladinRankAttribution from './PaladinRankAttribution'

export default function PaladinBuildComparator() {
  const [selected, setSelected] = useState('traditional-ret')
  const route = PALADIN_COMPARISON_ROUTES.find(item => item.id === selected)
  const twist = snapshotGate('twist_of_light')
  const shock = snapshotGate('holy_shock')
  const vigil = snapshotGate('light_s_vigil')
  return <main className="beta-page paladin-comparator" data-surface="paladin-build-comparator">
    <header className="guide-nav shell"><a className="brand" href="/">BUILD<b>FORGE</b></a><nav aria-label="Paladin navigation"><a href="/wow-forever-paladin-builds">Paladin Builds</a><a href="/paladin#calculator">Calculator</a><a href="/wow-forever-paladin-beta-talent-changes#build-impact">Patch Impact</a></nav></header>
    <section className="beta-hero shell"><div className="beta-hero-copy"><div className="eyebrow">Compare routes · standard progression</div><h1>WoW Forever Paladin Build Comparator</h1><p>Traditional Ret, Holy Shock and Twist of Light: compare point budgets, talent order and planning tradeoffs before opening the calculator.</p><p><strong>Level 30 · 21 points</strong> · Reviewed structure: 70245 · Planning examples reviewed October 5, 2026.</p><p>These are allocation comparisons, not DPS rankings. Current rank text has separate community evidence; official tuning is tracked separately. A legal snapshot route does not prove current in-game performance or availability.</p></div></section>
    <section className="shell beta-detail-block"><h2>What can fit in 21 points?</h2><div className="decision-table-scroll"><table className="decision-table"><caption>Reviewed 70245 talent gates, excluding Legacy perks</caption><thead><tr><th scope="col">Talent</th><th scope="col">Minimum tree points including talent</th><th scope="col">Standard level floor</th><th scope="col">Fits Level 30?</th></tr></thead><tbody>{[shock, twist, vigil].map(gate => <tr key={gate.talent.id}><th scope="row">{gate.talent.name}</th><td>{gate.points}</td><td>{gate.minimumLevel}</td><td>{gate.withinLevel30Budget ? 'Yes, in this snapshot' : 'No, exceeds 21 points'}</td></tr>)}</tbody></table></div><p>These are floors from reviewed client positions; the point budget assumes normal progression. Prerequisites can impose additional constraints. The two editable routes below are replayed through the planner one point at a time.</p></section>
    <section className="shell beta-detail-block"><h2>Compare the tradeoffs</h2><div className="decision-grid">{PALADIN_COMPARISON_ROUTES.map(item => <article key={item.id}><h3>{item.label} · {item.allocation}</h3><p>{item.style}</p><p><strong>Core talents:</strong> {item.core.map(id => talents.find(t => t.id === id)!.name).join(', ')}.</p><p>{item.weapon}</p><p>{item.stats}</p><small>{item.evidence}</small></article>)}<article><h3>Twist of Light · unavailable at 21 points in this snapshot</h3><p>The recorded talent adds an Echo when replacing a Seal. Its {twist.points}-point floor is above the standard Level 30 budget, so no Level 30 Twist allocation is offered.</p><p>Choosing Traditional Ret does not mean you must take this capstone. Whether a higher-level twisting route outperforms another setup requires current gameplay evidence.</p><a href="/wow-forever-retribution-paladin-talents">Inspect Retribution talent evidence</a></article></div></section>
    <section className="shell beta-detail-block"><h2>Choose a route to replay</h2><div className="leveling-milestones" aria-label="Comparison route">{[...PALADIN_COMPARISON_ROUTES.map(item => ({ id: item.id, label: item.label })), { id: 'twist', label: 'Twist of Light' }].map(item => <button type="button" key={item.id} aria-pressed={selected === item.id} onClick={() => { if (selected === item.id) return; setSelected(item.id); track('build_comparison_select', { class: 'paladin', route_id: item.id, level: 30 }) }}>{item.label}</button>)}</div></section>
    {route ? <PaladinRouteTimeline key={route.id} steps={route.steps} routeId={route.id} title={`${route.label}: Level 10–30`} evidence={route.evidence} /> : <section className="shell beta-detail-block" role="status"><h2>Twist needs at least {twist.points} points in the imported tree</h2><p>No loadable Level 30 route is available. The minimum standard level from this gate is {twist.minimumLevel}; live-game confirmation is still needed before treating the modeled point budget as an actual unlock.</p><a href="/wow-forever-paladin-talents">Review the snapshot and data status</a></section>}
    <section className="shell beta-detail-block"><h2>Does Retribution need Holy talents?</h2><p>The Traditional Ret example spends all 21 points in Retribution. The Holy Shock example spends all 21 in Holy. In this snapshot, the 21-point Holy Shock gate leaves no points for Retribution at Level 30. These are separate planning choices, not a requirement to mix both trees.</p><h2>How should I compare them in game?</h2><p>Keep level, equipment and encounter conditions the same. Record fight time, mana remaining and healing needed across several attempts. This tool does not estimate damage, threat or win rates without validated inputs.</p><h2>Sources and review limits</h2><p><a href="https://wago.tools/db2/TraitNode/csv?build=1.60.1.70245" target="_blank" rel="noreferrer">Reviewed 70245 client structure</a> · <a href="https://mobalytics.gg/wow-forever/classes/paladin-leveling-guide" target="_blank" rel="noreferrer">Community Ret route source</a> · <a href="/wow-forever-paladin-beta-talent-changes">Official patch notes and historical diffs</a>.</p><p>The Holy Shock point order is a BuildForgeTools editorial example. Neither forum opinions nor a source's changing live page replace the preserved client dataset.</p><PaladinRankAttribution /></section>
    <SiteFooter links={[{ href: '/wow-forever-retribution-paladin-build', label: 'Retribution Build' }, { href: '/wow-forever-paladin-build', label: 'Holy Build' }, { href: '/wow-forever-paladin-leveling-build', label: 'Leveling Route' }]} />
  </main>
}
