import { afterEach, expect, it } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import PlanningToolsPage from './PlanningToolsPage'
afterEach(cleanup)
it('opens the confirmed Ruins dungeon with a current-cap route and calculator snapshot', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  expect(screen.getByRole('button',{name:/Ruins of Lordaeron/i}).getAttribute('aria-pressed')).toBe('true')
  expect(within(screen.getByRole('region',{name:'Ruins of Lordaeron planning context'})).getByRole('link',{name:/Blizzard Beta announcement/i}).getAttribute('href')).toContain('worldofwarcraft.blizzard.com')
  fireEvent.change(screen.getByLabelText('Class'),{target:{value:'warrior'}})
  const link = screen.getByRole('link',{name:/Edit level 20 snapshot/i})
  expect(link.getAttribute('href')).toContain('/warrior?build=')
  expect(screen.getByText('11 talent points')).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:'Level 15 milestone'}))
  expect(screen.getByRole('link',{name:/Edit level 15 snapshot/i})).toBeTruthy()
  expect(screen.getByText('6 talent points')).toBeTruthy()
  expect(screen.getByText(/Next point · Level 16/i)).toBeTruthy()
  fireEvent.change(screen.getByLabelText('Your level'),{target:{value:'17'}})
  expect(screen.getByRole('link',{name:/Edit level 17 snapshot/i})).toBeTruthy()
  expect(screen.getByText('8 talent points')).toBeTruthy()
  expect(screen.getByRole('button',{name:/Excavation Site/i}).hasAttribute('disabled')).toBe(false)
})
it('uses one dungeon context for faction quests, role and level while keeping unreviewed routes locked', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  expect(screen.getAllByLabelText('Your level')).toHaveLength(1)
  expect(screen.getAllByLabelText('Faction view')).toHaveLength(1)
  expect(screen.getByRole('article', {name:'Ruins of Lordaeron'})).toBeTruthy()
  expect(screen.queryByRole('article', {name:'Hall of Thanes'})).toBeNull()
  fireEvent.change(screen.getByLabelText('Faction view'), {target:{value:'alliance'}})
  expect(screen.queryByRole('checkbox', {name:/The Wrath of Rath'mael/})).toBeNull()
  expect(screen.getByRole('checkbox', {name:/Crest of Lordaeron/})).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:'Heal'}))
  expect(screen.getByText(/Ruins of Lordaeron · Level 20 · Heal · Alliance/)).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:/Excavation Site/i}))
  expect(screen.getByRole('article', {name:'Excavation Site: Wetlands'})).toBeTruthy()
  expect(screen.queryByRole('article', {name:'Ruins of Lordaeron'})).toBeNull()
  expect(screen.getByText(/Excavation Site: Wetlands · Level 26 · Heal · Alliance/)).toBeTruthy()
  expect(screen.getByRole('status').textContent).toMatch(/Build routes await review/i)
  expect(document.querySelectorAll('[data-tool-route]')).toHaveLength(0)
})
it('clears XP inputs when the selected dungeon context changes', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  fireEvent.click(screen.getByRole('button',{name:'Try illustrative numbers'}))
  expect((screen.getByLabelText('First-run total XP') as HTMLInputElement).value).toBe('12000')
  fireEvent.click(screen.getByRole('button',{name:/Hall of Thanes/i}))
  expect((screen.getByLabelText('First-run total XP') as HTMLInputElement).value).toBe('')
  expect(screen.getByText(/Hall of Thanes · Level 13 · Tank · All factions/)).toBeTruthy()
})
it('keeps Ruins quest prep and XP planning available at 21–22 without offering an unreviewed build route', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  const level = screen.getByLabelText('Your level') as HTMLInputElement
  expect(level.max).toBe('22')
  fireEvent.change(level,{target:{value:'22'}})
  expect(screen.getByRole('article',{name:'Ruins of Lordaeron'})).toBeTruthy()
  expect(screen.getByText(/Ruins of Lordaeron · Level 22 · Tank · All factions/)).toBeTruthy()
  expect(screen.getByRole('status').textContent).toMatch(/Build routes are reviewed only through level 20/i)
  expect(document.querySelectorAll('[data-tool-route]')).toHaveLength(0)
  expect(screen.queryByRole('button',{name:'Show all classes'})).toBeNull()
})
it('marks Excavation as a selectable prep destination without a lock icon', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  const excavation = screen.getByRole('button',{name:/Excavation Site/i})
  expect(excavation.textContent).toMatch(/Prep available · build routes awaiting review/)
  expect(excavation.querySelector('.lucide-lock')).toBeNull()
  expect(excavation.querySelector('.lucide-map-pin')).toBeTruthy()
})
it('offers the node-reviewed Protection route for a dungeon tank', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  const protection = document.querySelector('[data-tool-route="paladin-protection"]') as HTMLElement
  expect(protection).toBeTruthy()
  expect(within(protection).getByRole('link',{name:/Edit level 20 snapshot/i}).getAttribute('href')).toContain('redoubt.5')
  fireEvent.click(screen.getByRole('button',{name:'Heal'}))
  expect(screen.getByRole('heading',{name:/Ruins of Lordaeron: Heal routes/i})).toBeTruthy()
  fireEvent.click(screen.getByRole('button',{name:/Hall of Thanes/i}))
  expect(screen.getByRole('button',{name:/Hall of Thanes/i}).getAttribute('aria-pressed')).toBe('true')
  expect(screen.getByText('Level 13 · 4 points')).toBeTruthy()
})
it('class picker shows explainable matches and a useful empty state', () => {
  render(<PlanningToolsPage tool="class-picker" />)
  fireEvent.change(screen.getByLabelText('Party role'),{target:{value:'heal'}})
  fireEvent.change(screen.getByLabelText('Activity'),{target:{value:'dungeon'}})
  expect(screen.getAllByText('Healing role matches your choice.').length).toBeGreaterThan(1)
  fireEvent.change(screen.getByLabelText('Combat style'),{target:{value:'melee'}})
  expect(screen.getByText(/No published route matches all three choices/i)).toBeTruthy()
  expect(screen.getByRole('button',{name:'Reset preferences'})).toBeTruthy()
})
it('shows a Hunter route with removed talents as historical and opens a blank calculator', () => {
  render(<PlanningToolsPage tool="dungeon-finder" />)
  fireEvent.click(screen.getByRole('button', {name:'DPS'}))
  fireEvent.change(screen.getByLabelText('Class'), {target:{value:'hunter'}})
  const card = document.querySelector('[data-tool-route="hunter-hunter-dungeon-build"]') as HTMLElement
  expect(card).toBeTruthy()
  expect(screen.getByText(/^\d+ results$/)).toBeTruthy()
  expect(within(card).getByText(/Aimed Shot.*removed/i)).toBeTruthy()
  expect(within(card).getByRole('link', {name:/Open blank Hunter Calculator/i}).getAttribute('href')).toBe('/hunter?build=#class-calculator')
  expect(within(card).queryByRole('link', {name:/Edit level 20 snapshot/i})).toBeNull()
})
