import { ArrowRight, BookOpen, Compass, Layers, ShieldCheck, Sprout, Store } from 'lucide-react'
import SiteFooter from './SiteFooter'
import { DISCOVERY_PAGES, discoveryClasses, discoveryGroups, type DiscoveryId } from './data/siteDiscovery'

const classes = discoveryClasses()
const groups = discoveryGroups()
const classStartingPoints: Record<string, string> = {
  paladin: 'Compare Holy, Protection and Retribution. The Paladin leveling route now has a point-by-point Level 10–30 timeline; its talent tooltips still identify the older imported client snapshot.',
  warrior: 'Compare Arms, Fury and Protection paths for leveling, damage or tanking. Start with a published route, then inspect every rank in the editable calculator.',
  mage: 'Choose between Arcane, Fire and Frost routes. The builds show editorial choices; the talent reference and calculator let you check the underlying nodes.',
  hunter: 'Explore Beast Mastery, Marksmanship and Survival. Use the build routes to compare playstyles, then change the allocation in the calculator.',
  druid: 'Explore Balance, Feral and Restoration routes. Compare your preferred role before opening a talent allocation.',
  priest: 'Compare Discipline, Holy and Shadow routes. Start from a healing or damage goal, then inspect the talent reference.',
  rogue: 'Explore Assassination, Combat and Subtlety. Browse a leveling or PvP route and test a different point allocation.',
  shaman: 'Compare Elemental, Enhancement and Restoration. Follow a published starting route and review the talent evidence before editing.',
  warlock: 'Explore Affliction, Demonology and Destruction. Compare the available builds and adjust your own talent path.',
}
function ClassCards() {
  return <div className="sd-class-grid">{classes.map(c => <article className="sd-class-card" key={c.id}>
    <div className="sd-class-art">{c.image && <img src={c.image} alt="" loading="lazy" />}<h2>{c.name}</h2></div>
    <div className="sd-class-info"><p className="sd-branches">{c.branches.join(' · ')}</p><p className="sd-class-start">{classStartingPoints[c.id]}</p><nav aria-label={`${c.name} tools`}>{c.links.map(l => <a href={l.href} key={l.href}>{l.label}<ArrowRight size={14} /></a>)}</nav></div>
  </article>)}</div>
}
export default function SiteDiscoveryPage({ pageId }: { pageId: DiscoveryId }) {
  const page = DISCOVERY_PAGES.find(p => p.id === pageId)!
  return <div className="site-discovery" data-experience-kind={`discovery-${pageId}`}>
    <header className="sd-header"><a className="sd-brand" href="/"><img src="/images/icons/paladin-shield.png" alt="" />BUILD<b>FORGE</b><small>TOOLS</small></a><nav aria-label="Site discovery"><a href="/wow-forever-classes" aria-current={pageId === 'classes' ? 'page' : undefined}>WoW classes</a><a href="/wow-forever-builds" aria-current={pageId === 'builds' ? 'page' : undefined}>WoW builds</a><a href="/emberville">Emberville</a></nav></header>
    <main className="sd-main"><div className="sd-intro"><p className="sd-kicker">{pageId === 'home' ? 'THE BUILD PLANNING WORKBENCH' : 'WORLD OF WARCRAFT FOREVER'}</p><h1>{page.h1}</h1><p>{pageId === 'home' ? 'Talent calculators, editable routes and source-linked references. Pick a tool and start planning.' : page.description}</p></div>
      {pageId === 'home' ? <>
        <section className="sd-games" aria-label="Choose a game"><article className="sd-game sd-wow"><img className="sd-game-art" src="/images/hero/hero-paladin.webp" alt="" /><div className="sd-game-content"><p className="sd-kicker">TALENTS · BUILDS · PROGRESSION</p><h2>WoW Forever</h2><p>Explore nine classes. Inspect the talent evidence, follow an editorial route, then make the allocation yours.</p><nav className="sd-paladin-feature" aria-label="Featured Paladin tools"><span>Start with Paladin</span><a href="/paladin">WoW Forever Paladin Talent Calculator <ArrowRight size={15} /></a><a href="/wow-forever-paladin-builds">Paladin Builds <ArrowRight size={15} /></a></nav><a className="sd-primary" href="/wow-forever-classes">Choose your class <ArrowRight size={17} /></a><a className="sd-secondary" href="/wow-forever-builds">Browse builds by playstyle <ArrowRight size={15} /></a></div><nav className="sd-quick" aria-label="Class calculators">{classes.flatMap(c => c.links.filter(l => l.label === 'Calculator').map(l => <a href={l.href} key={l.href}>{c.name}</a>))}</nav></article>
        <article className="sd-game sd-ember"><img className="sd-game-art" src="/images/emberville/planner-hero.jpg" alt="" /><div className="sd-game-content"><p className="sd-kicker">PLANNER PREVIEW · CORE MECHANICS</p><h2>Emberville</h2><p>Save a combat direction and planning notes while class and skill records are under review. Explore the published core mechanics references.</p><a className="sd-primary" href="/emberville">Open the planner <ArrowRight size={17} /></a><a className="sd-secondary" href="/emberville-builds">Explore build planning <ArrowRight size={15} /></a></div><nav className="sd-quick" aria-label="Emberville references"><a href="/emberville-classes">Classes</a><a href="/emberville-skill-inheritance">Skill inheritance</a></nav></article>
        <article className="sd-game sd-glimmerwick"><div className="sd-garden-art" aria-hidden="true"><Sprout size={112} strokeWidth={1} /></div><div className="sd-game-content"><p className="sd-kicker">GARDEN PLANNER · YOUR OBSERVATIONS</p><h2>Songs of Glimmerwick</h2><p>Plan planting days with your own crop timings. Estimate harvests, keep garden notes, and export your plan. No unverified crop values are filled in.</p><a className="sd-primary" href="/songs-of-glimmerwick">Open the garden planner <ArrowRight size={17} /></a></div><nav className="sd-quick" aria-label="Songs of Glimmerwick guides and tools"><a href="/songs-of-glimmerwick-first-days">First Days Checklist</a><a href="/songs-of-glimmerwick-spellcasting">Spellcasting Basics</a><a href="/songs-of-glimmerwick-garden-well">Garden Well Sell Planner</a></nav></article>
        <article className="sd-game sd-nivalis"><div className="sd-nivalis-art" aria-hidden="true"><Store size={120} strokeWidth={1}/></div><div className="sd-game-content"><p className="sd-kicker">BUSINESS PROFIT · SCENARIO COMPARISON</p><h2>Nivalis Nights</h2><p>Work out net profit and break-even sales with your own prices and costs. Compare two business ideas and keep a local planning sheet.</p><a className="sd-primary" href="/nivalis-nights-profit-calculator">Open the profit calculator <ArrowRight size={17}/></a></div></article></section>
        <section className="sd-tool-strip" aria-label="How to use BuildForgeTools">{[{ icon: Compass, title: 'Choose a starting point', text: 'Find a class or browse leveling, PvP and group-role routes.', href: '/wow-forever-builds', label: 'Browse routes' }, { icon: Layers, title: 'Make the points yours', text: 'Open published allocations in the calculator, adjust talents and share your setup.', href: '/wow-forever-classes', label: 'Find a calculator' }, { icon: ShieldCheck, title: 'Check the evidence', text: 'Client records and editorial choices stay distinct. Source limits remain visible.', href: '/about', label: 'About the project' }].map(({ icon: Icon, ...item }) => <article key={item.title}><Icon size={23} /><h2>{item.title}</h2><p>{item.text}</p><a href={item.href}>{item.label}<ArrowRight size={14} /></a></article>)}</section>
      </> : pageId === 'classes' ? <><section className="sd-class-orientation" aria-labelledby="sd-class-orientation-title"><div><p className="sd-kicker">CHOOSE A STARTING POINT</p><h2 id="sd-class-orientation-title">Find the right route for your next build</h2><p>Each class card opens an editable talent calculator, a build hub, a talent reference and a leveling route where those pages have been published. Choose a specialization first, then compare the route with the talent evidence and change the points yourself.</p><p>Some published class examples are Level 20 snapshots from an older client dataset. Their point budgets describe those examples, not the current Beta level cap. Check each page’s source and status before using a route in game. Paladin has a separate reviewed Level 10–30 community timeline.</p></div><nav aria-label="Browse by goal"><a href="/wow-forever-builds#leveling">Leveling routes <ArrowRight size={15}/></a><a href="/wow-forever-builds#pvp">PvP builds <ArrowRight size={15}/></a><a href="/wow-forever-builds#dungeon">Dungeon roles <ArrowRight size={15}/></a><a href="/wow-forever-paladin-leveling-build">Paladin Level 10–30 <ArrowRight size={15}/></a></nav></section><div className="sd-section-bar"><span>{String(classes.length).padStart(2, '0')} CLASSES</span><a href="/wow-forever-builds">Prefer to start with a playstyle? <ArrowRight size={15} /></a></div><ClassCards /></> : <><aside className="sd-paladin-hub"><div><p className="sd-kicker">FEATURED CLASS</p><h2>Start with Paladin builds</h2><p>Explore Holy, Protection, and Retribution routes, then edit an allocation in the talent calculator.</p></div><a href="/wow-forever-paladin-builds">Browse WoW Forever Paladin Builds <ArrowRight size={17} /></a></aside><nav className="sd-intent-nav" aria-label="Build intents">{groups.map(g => <a href={`#${g.id}`} key={g.id}>{g.label}<ArrowRight size={14} /></a>)}</nav><div className="sd-build-groups">{groups.map((g, i) => <section className="sd-build-group" id={g.id} key={g.id}><div className="sd-group-heading"><span>0{i + 1}</span><div><h2>{g.label}</h2><p>{g.description}</p></div></div><div className="sd-build-classes">{g.classGroups.map(c => <article className="sd-build-class" key={c.id}><h3>{c.name}</h3><div className="sd-build-links">{c.links.map(l => <a href={l.href} key={l.href}>{l.label}<ArrowRight size={15} /></a>)}</div></article>)}</div></section>)}</div></>}
      <nav className="sd-new-tools" aria-label="Interactive planning tools"><a href="/wow-forever-dungeon-build-finder">Find a dungeon build <ArrowRight size={17}/></a><a href="/wow-forever-class-picker">Match your class and playstyle <ArrowRight size={17}/></a></nav>
      <aside className="sd-source-note"><BookOpen size={21} /><p><strong>A planning tool, with evidence in view.</strong> WoW routes use published datasets and editorial allocations. Planning caps are dataset assumptions, and build examples are not popularity or performance rankings.</p></aside>
    </main><SiteFooter discovery />
  </div>
}
