import { ArrowRight, BookOpen, Compass, Layers, ShieldCheck } from 'lucide-react'
import SiteFooter from './SiteFooter'
import { DISCOVERY_PAGES, discoveryClasses, discoveryGroups, type DiscoveryId } from './data/siteDiscovery'

const classes = discoveryClasses()
const groups = discoveryGroups()
function ClassCards() {
  return <div className="sd-class-grid">{classes.map(c => <article className="sd-class-card" key={c.id}>
    <div className="sd-class-art">{c.image && <img src={c.image} alt="" loading="lazy" />}<h2>{c.name}</h2></div>
    <div className="sd-class-info"><p>{c.branches.join(' · ')}</p><nav aria-label={`${c.name} tools`}>{c.links.map(l => <a href={l.href} key={l.href}>{l.label}<ArrowRight size={14} /></a>)}</nav></div>
  </article>)}</div>
}
export default function SiteDiscoveryPage({ pageId }: { pageId: DiscoveryId }) {
  const page = DISCOVERY_PAGES.find(p => p.id === pageId)!
  return <div className="site-discovery" data-experience-kind={`discovery-${pageId}`}>
    <header className="sd-header"><a className="sd-brand" href="/"><img src="/images/icons/paladin-shield.png" alt="" />BUILD<b>FORGE</b><small>TOOLS</small></a><nav aria-label="Site discovery"><a href="/wow-forever-classes" aria-current={pageId === 'classes' ? 'page' : undefined}>WoW classes</a><a href="/wow-forever-builds" aria-current={pageId === 'builds' ? 'page' : undefined}>WoW builds</a><a href="/emberville">Emberville</a></nav></header>
    <main className="sd-main"><div className="sd-intro"><p className="sd-kicker">{pageId === 'home' ? 'THE BUILD PLANNING WORKBENCH' : 'WORLD OF WARCRAFT FOREVER'}</p><h1>{page.h1}</h1><p>{pageId === 'home' ? 'Talent calculators, editable routes and source-linked references. Pick a tool and start planning.' : page.description}</p></div>
      {pageId === 'home' ? <>
        <section className="sd-games" aria-label="Choose a game"><article className="sd-game sd-wow"><img className="sd-game-art" src="/images/hero/hero-paladin.webp" alt="" /><div className="sd-game-content"><p className="sd-kicker">TALENTS · BUILDS · PROGRESSION</p><h2>WoW Forever</h2><p>Explore nine classes. Inspect the talent evidence, follow an editorial route, then make the allocation yours.</p><a className="sd-primary" href="/wow-forever-classes">Choose your class <ArrowRight size={17} /></a><a className="sd-secondary" href="/wow-forever-builds">Browse builds by playstyle <ArrowRight size={15} /></a></div><nav className="sd-quick" aria-label="Class calculators">{classes.flatMap(c => c.links.filter(l => l.label === 'Calculator').map(l => <a href={l.href} key={l.href}>{c.name}</a>))}</nav></article>
        <article className="sd-game sd-ember"><img className="sd-game-art" src="/images/emberville/planner-hero.jpg" alt="" /><div className="sd-game-content"><p className="sd-kicker">PLANNER PREVIEW · CORE MECHANICS</p><h2>Emberville</h2><p>Save a combat direction and planning notes while class and skill records are under review. Explore the published core mechanics references.</p><a className="sd-primary" href="/emberville">Open the planner <ArrowRight size={17} /></a><a className="sd-secondary" href="/emberville-builds">Explore build planning <ArrowRight size={15} /></a></div><nav className="sd-quick" aria-label="Emberville references"><a href="/emberville-classes">Classes</a><a href="/emberville-skill-inheritance">Skill inheritance</a></nav></article></section>
        <section className="sd-tool-strip" aria-label="How to use BuildForgeTools">{[{ icon: Compass, title: 'Choose a starting point', text: 'Find a class or browse leveling, PvP and group-role routes.', href: '/wow-forever-builds', label: 'Browse routes' }, { icon: Layers, title: 'Make the points yours', text: 'Open published allocations in the calculator, adjust talents and share your setup.', href: '/wow-forever-classes', label: 'Find a calculator' }, { icon: ShieldCheck, title: 'Check the evidence', text: 'Client records and editorial choices stay distinct. Source limits remain visible.', href: '/about', label: 'About the project' }].map(({ icon: Icon, ...item }) => <article key={item.title}><Icon size={23} /><h2>{item.title}</h2><p>{item.text}</p><a href={item.href}>{item.label}<ArrowRight size={14} /></a></article>)}</section>
      </> : pageId === 'classes' ? <><div className="sd-section-bar"><span>{String(classes.length).padStart(2, '0')} CLASSES</span><a href="/wow-forever-builds">Prefer to start with a playstyle? <ArrowRight size={15} /></a></div><ClassCards /></> : <><nav className="sd-intent-nav" aria-label="Build intents">{groups.map(g => <a href={`#${g.id}`} key={g.id}>{g.label}<ArrowRight size={14} /></a>)}</nav><div className="sd-build-groups">{groups.map((g, i) => <section className="sd-build-group" id={g.id} key={g.id}><div className="sd-group-heading"><span>0{i + 1}</span><div><h2>{g.label}</h2><p>{g.description}</p></div></div><div className="sd-build-classes">{g.classGroups.map(c => <article className="sd-build-class" key={c.id}><h3>{c.name}</h3><div className="sd-build-links">{c.links.map(l => <a href={l.href} key={l.href}>{l.label}<ArrowRight size={15} /></a>)}</div></article>)}</div></section>)}</div></>}
      <aside className="sd-source-note"><BookOpen size={21} /><p><strong>A planning tool, with evidence in view.</strong> WoW routes use published datasets and editorial allocations. Planning caps are dataset assumptions, and build examples are not popularity or performance rankings.</p></aside>
    </main><SiteFooter discovery />
  </div>
}
