import { ArrowRight, Shield, Swords, Zap } from 'lucide-react'
import SiteFooter from './SiteFooter'
import { WARRIOR_BUILD_PAGES, warriorPlannerHref } from './data/warriorPages'

const specPages = WARRIOR_BUILD_PAGES.filter((page) => page.id !== 'leveling')
const icons = { arms: Swords, fury: Zap, protection: Shield }

export default function WarriorBuildsHub() {
  return <main className="warrior-page warrior-editorial"><header className="warrior-nav shell"><a className="warrior-brand" href="/warrior"><Swords /><span>BUILD<b>FORGE</b></span></a><nav><a href="/warrior">Talent Calculator</a><a href="/wow-forever-warrior-leveling-build">Leveling</a><a href="/paladin">Paladin</a></nav></header><section className="warrior-hub-hero"><div className="shell"><p className="warrior-kicker">Beta Build 69913</p><h1>WoW Forever Warrior Builds<br /><span>&amp; Talent Calculator</span></h1><p>Choose an Arms, Fury, or Protection Level 20 starter, inspect every point, and customize it in the Warrior planner.</p><a className="button warrior-primary" href="/warrior">Open Warrior Talent Calculator <ArrowRight /></a></div></section><section className="shell warrior-spec-cards"><div className="section-heading"><p className="warrior-kicker">Current-cap starters</p><h2>Choose a Warrior specialization</h2></div><div>{specPages.map((page) => { const Icon = icons[page.preset.branch]; return <article key={page.id}><Icon /><span>{page.preset.allocation}</span><h2><a href={`/${page.slug}`}>{page.preset.shortTitle.replace(' Leveling', ' Warrior Build').replace(' Tank', ' Warrior Build')}</a></h2><p>{page.preset.summary}</p><a href={`/${page.slug}`}>View build <ArrowRight /></a></article> })}</div></section><section className="shell warrior-popular"><div><h2>Warrior Leveling Build</h2><p>Compare all three 11-point routes under the current Level 20 Beta cap.</p><a href="/wow-forever-warrior-leveling-build">Compare leveling routes <ArrowRight /></a></div><div><h2>Create your own Warrior build</h2><p>Start from a blank tree or load a preset, then share an exact build URL.</p><a href={warriorPlannerHref(specPages[0].preset)}>Open a starter in the calculator <ArrowRight /></a></div></section><section className="shell warrior-copy"><h2>About these Warrior builds</h2><p>BuildForgeTools separates client-derived talent facts from community build recommendations. The 53-node Warrior dataset was checked through build 1.60.1.69913. Build routes remain editable testing ideas rather than official or guaranteed best builds.</p></section><SiteFooter links={[{ href: '/warrior', label: 'Warrior Calculator' }, { href: '/wow-forever-warrior-leveling-build', label: 'Warrior Leveling' }, { href: '/paladin', label: 'Paladin Calculator' }]} /></main>
}

